import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import path from 'path'
import fs from 'fs'

const copyFiles = {
  name: 'copy-files',
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length) {
        console.log('[copy-files-plugin][error] build failed, skipping file copy')
        return
      }

      try {
        const destDir = path.resolve(process.env.OBSIDIAN_VAULT_DIR)
        if (!fs.existsSync(destDir)) {
          throw new Error('Obsidian vault does not exist')
        }

        const pluginDir = destDir + '/.obsidian/plugins/obsidian-bible-kit'
        if (!fs.existsSync(pluginDir)) {
          fs.mkdirSync(pluginDir, { recursive: true })
        }

        fs.copyFileSync('main.js', pluginDir + '/main.js')
        fs.copyFileSync('styles.css', pluginDir + '/styles.css')
        fs.copyFileSync('manifest.json', pluginDir + '/manifest.json')

        console.log(`[copy-files-plugin] copied main.js, styles.css, and manifiest.json to ${pluginDir}`)
      } catch (err) {
        console.log('[copy-files-plugin][error] copying file:', err)
      }
    })
  }
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  plugins: []
})

if (prod) {
  await context.rebuild()
  process.exit(0)
} else {
  await context.watch()
}
