import builtins from 'builtin-modules'
import esbuild from 'esbuild'
import path from 'path'
import process from 'process'
import { fileURLToPath } from 'url'

const pluginDir = path.dirname(fileURLToPath(import.meta.url))

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
  absWorkingDir: pluginDir,
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  jsx: 'automatic',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: path.join(pluginDir, 'main.js'),
  minify: prod,
  loader: {
    '.wasm': 'binary',
  },
})

if (prod) {
  await context.rebuild()
  process.exit(0)
} else {
  await context.watch()
}
